"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Logo } from "@/components";
import { AuthContext } from "./context/authContext";
import { useEffect, useState } from "react";
import axios from "axios";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [profile, setProfile] = useState();

  const fetchProfileData = async () => {
    try {
      const response = await axios.get(`http://localhost:8000/profile`);
      console.log(response);
      // setProfile(response.data);
    } catch (error) {
      console.error(error, "err");
    }
  };

  useEffect(() => {
    fetchProfileData();
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContext.Provider value={{ profile, setProfile }}>
          <Logo />
          {children}
        </AuthContext.Provider>
      </body>
    </html>
  );
}
