"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Logo } from "@/components";
import { Dispatch, SetStateAction, useEffect, useState } from "react";
import axios from "axios";
import { AuthContext } from "@/context/authContext";
import { objectInputType, objectOutputType } from "zod";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

type ProfileDataTypes = {
  avatarImage: string;
  profileName: string;
  socialMediaURL: string;
  about: string;
};
type Types = {
  profile: ProfileDataTypes;
  setProfile: (profile: ProfileDataTypes) => void;
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [profile, setProfile] = useState<Types>();

  const fetchProfileData = async () => {
    try {
      const response = await axios.get(`http://localhost:8000/profile`, {
        withCredentials: true,
      });
      setProfile(response.data);
      console.log(response.data);
    } catch (error) {
      console.error(error, "err");
    }
  };

  useEffect(() => {
    fetchProfileData();
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0`}
      >
        <AuthContext.Provider
          value={profile ? { profile, setProfile } : undefined}
        >
          <Logo />
          {children}
        </AuthContext.Provider>
      </body>
    </html>
  );
}
